version: '3.8'
services: 
    web:
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: php747-apache
        links:
            - db
        volumes: 
            - ./:/var/www/html/
        ports:
            - 8000:80
    db:
        container_name: mysql8020
        image: mysql:8.0.20
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        volumes:
            - "./mysql-data/db:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: myl0g1n
            MYSQL_DATABASE: test_db
            MYSQL_USER: devuser
            MYSQL_PASSWORD: devpass
        ports:
             - 6033:3306
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - db
        ports:
            - 8001:80
        environment: 
            MYSQL_USER: devuser
            MYSQL_PASSWORD: devpass
            MYSQL_ROOT_PASSWORD: myl0g1n